### ISSUE TITLE
"Component to inherit from" settings does not seem to work

### ISSUE THREAD

**Issue by webdif** [germtb/react-function-to-class#1]
I love this little atom plugin. But I convert my functions to `React.PureComponent` even if I set the setting to `React.Component`.

I looked at [the code](https://github.com/germtb/react-function-to-class/blob/master/lib/react-function-to-class.js), but everything seems correct. So I don't know why this does not work for me…
Do you have any ideas? 🙏 

Thanks a lot for your work on this package 👌

**Comment by germtb** [comment]
Thanks for letting me know, it was a regression. It should be fixed as of v0.2.4

**Comment by webdif** [comment]
It works like a charm. Thank you!
